#!/usr/bin/env python3
"""Build a Preferred Partner mapping form from exported CompanyCam users.

Input is the ignored local export generated by scripts/export_users.py.
Output is ignored local CSV/Markdown under exports/ for manual review.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


INPUT_FIELDS = [
    "id",
    "display_name",
    "email_address",
    "phone_number",
    "status",
    "user_role",
    "user_url",
]

OUTPUT_FIELDS = [
    "companycam_user_id",
    "companycam_display_name",
    "companycam_email",
    "companycam_phone",
    "companycam_status",
    "companycam_role",
    "companycam_user_url",
    "pp_match_status",
    "pp_name",
    "pp_company_name",
    "pp_service_type",
    "pp_phone",
    "pp_email",
    "jobber_vendor_id",
    "heypros_profile_url",
    "preferred_partner_tier",
    "default_service_area",
    "notes",
]


def build_row(row: dict[str, str]) -> dict[str, str]:
    return {
        "companycam_user_id": row.get("id", ""),
        "companycam_display_name": row.get("display_name", ""),
        "companycam_email": row.get("email_address", ""),
        "companycam_phone": row.get("phone_number", ""),
        "companycam_status": row.get("status", ""),
        "companycam_role": row.get("user_role", ""),
        "companycam_user_url": row.get("user_url", ""),
        "pp_match_status": "",
        "pp_name": "",
        "pp_company_name": "",
        "pp_service_type": "",
        "pp_phone": "",
        "pp_email": "",
        "jobber_vendor_id": "",
        "heypros_profile_url": "",
        "preferred_partner_tier": "",
        "default_service_area": "",
        "notes": "",
    }


def read_users(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        missing = [field for field in INPUT_FIELDS if field not in (reader.fieldnames or [])]
        if missing:
            raise RuntimeError(f"{path} is missing expected fields: {', '.join(missing)}")
        return list(reader)


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def write_notes(path: Path, active_count: int, full_count: int) -> None:
    content = f"""# CompanyCam Preferred Partner Mapping Form

Generated from `exports/companycam_users.csv`.

## Files

- `companycam_pp_mapping_template_active.csv` - active CompanyCam users only ({active_count} rows)
- `companycam_pp_mapping_template_full.csv` - all exported CompanyCam users ({full_count} rows)

## Suggested Review Values

Use `pp_match_status` as the review decision column:

- `matched` - this CompanyCam user is a Preferred Partner and the PP identity is filled in
- `not_pp` - this user is not a Preferred Partner
- `needs_review` - possible PP, but identity is uncertain
- `duplicate` - duplicate CompanyCam user for the same person/company
- `inactive_old` - old/deleted account retained for history only

Fill in the PP columns where known. Leave unknown values blank instead of guessing.
"""
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=None,
        help="Path to companycam_users.csv. Defaults to exports/companycam_users.csv.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    source = args.source or repo_root / "exports" / "companycam_users.csv"
    users = read_users(source)

    active_users = [user for user in users if user.get("status") == "active"]
    active_rows = [build_row(user) for user in active_users]
    full_rows = [build_row(user) for user in users]

    export_dir = repo_root / "exports"
    active_path = export_dir / "companycam_pp_mapping_template_active.csv"
    full_path = export_dir / "companycam_pp_mapping_template_full.csv"
    notes_path = export_dir / "companycam_pp_mapping_template_README.md"

    write_csv(active_path, active_rows)
    write_csv(full_path, full_rows)
    write_notes(notes_path, len(active_rows), len(full_rows))

    print(f"Wrote active PP mapping template: {active_path} ({len(active_rows)} rows)")
    print(f"Wrote full PP mapping template: {full_path} ({len(full_rows)} rows)")
    print(f"Wrote notes: {notes_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
